version: "3.7"

services:
    hello-world:
        container_name: sound-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 4000:80
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
